// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPzE4sBdydn0CJ2KyXgj9PnXDyv3qp8a4',
    appId: '1:652245396163:web:8cfe499afc65bb7f735076',
    messagingSenderId: '652245396163',
    projectId: 'fireflutter-efd06',
    authDomain: 'fireflutter-efd06.firebaseapp.com',
    storageBucket: 'fireflutter-efd06.appspot.com',
    measurementId: 'G-G3D0VRVRQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2J7lMQNqhdrYzb73IAXl0AHCnqpHzDc',
    appId: '1:652245396163:android:beb99c27a2bce618735076',
    messagingSenderId: '652245396163',
    projectId: 'fireflutter-efd06',
    storageBucket: 'fireflutter-efd06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDww5BLlApzzUkdI2tnvxItIUHUzZez0xQ',
    appId: '1:652245396163:ios:9584829f4b92f079735076',
    messagingSenderId: '652245396163',
    projectId: 'fireflutter-efd06',
    storageBucket: 'fireflutter-efd06.appspot.com',
    iosClientId: '652245396163-tlfcuoetbk3t4p4lh6r5a7he20d79p09.apps.googleusercontent.com',
    iosBundleId: 'com.example.myspemob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDww5BLlApzzUkdI2tnvxItIUHUzZez0xQ',
    appId: '1:652245396163:ios:b6e458c6ca986bfb735076',
    messagingSenderId: '652245396163',
    projectId: 'fireflutter-efd06',
    storageBucket: 'fireflutter-efd06.appspot.com',
    iosClientId: '652245396163-hgo0i0b5qrtai8mg8b4jbjdib8pivf65.apps.googleusercontent.com',
    iosBundleId: 'com.example.myspemob.RunnerTests',
  );
}
